denker/urls.py
from django.conf.urls import url
from .views import detail_view, list_view

app_name = 'denker'

urlpatterns = [
    url(r'^(?P<denker_slug>[\w-]+)/$', detail_view, name='detail'),
    url(r'^$', list_view, name='list'),
]

faq/urls.py
from django.conf.urls import url
from .views import list_view

app_name = 'faq'

urlpatterns = [
    # url(r'^(?P<tag>#[\w-]+)$', list_view, name='list'),
    url(r'^$', list_view, name='list'),
]

framework/urls.py
from django.conf.urls import url
from .views import home_view
from django.http import HttpResponse

app_name = 'framework'

urlpatterns = [
    url(r'^$', home_view, name='home'),
    url(r'^googlee50af1936941f141.html$', lambda request: HttpResponse('google-site-verification: googlee50af1936941f141.html'))
]

orte/urls.py
from django.conf.urls import url
from .views import map_view, detail_view

app_name = 'orte'

urlpatterns = [
    url(r'^(?P<ort_slug>[\w-]+)/$', detail_view, name='detail'),
    url(r'^$', map_view, name='map'),
]

projekte/urls.py
from django.conf.urls import url
from .views import list_view, detail_view

app_name = 'projekte'

urlpatterns = [
    url(r'^$', list_view, name='list'),
    url(r'^(?P<projekt_slug>[\w-]+)/$', detail_view, name='detail'),
]

verlag/urls.py
from django.conf.urls import url
from .views import list_view

app_name = 'verlag'

urlpatterns = [
    url(r'^$', list_view, name='list'),
]

framework/models.py
from __future__ import unicode_literals
from django.db import models


class Ereignisse(models.Model):
    n = models.AutoField(primary_key=True)
    id = models.TextField()
    ereignis = models.TextField()
    jahr = models.IntegerField()
    denker = models.TextField()
    text_de = models.TextField()
    text_en = models.TextField()

    class Meta:
        managed = True
        db_table = 'ereignisse'


class StatischeInhalte(models.Model):
    n = models.AutoField(primary_key=True)
    id = models.TextField()
    info = models.TextField()

    class Meta:
        managed = True
        db_table = 'statische_inhalte'


class Zitate(models.Model):
    n = models.AutoField(primary_key=True)
    id = models.TextField()
    autor = models.TextField()
    text = models.TextField()
    quelle = models.TextField()

    class Meta:
        managed = True
        db_table = 'zitate'

framework/views.py
from django.shortcuts import render
from django.urls import reverse
from itertools import chain
import datetime
import locale

from denker.models import Denker
from verlag.models import Verlagsprogramm
from projekte.models import Projekte
from literatur.models import Buecher, Artikel
from .models import StatischeInhalte

from denker.utils import getImage
from projekte.utils import getPercent
from literatur.utils import createLink
from .utils import addLinks, getDays


def home_view(request):
    infotext = StatischeInhalte.objects.get(id="startseite")
    denker = Denker.objects.order_by("-id")[:4]
    verlag = Verlagsprogramm.objects.order_by("-id")[:2]
    projekt = Projekte.objects.order_by("-id")[0]
    literatur = chain(Buecher.objects.order_by("-id")[:2], Artikel.objects.order_by("-id")[:2])

    for denk in denker:
        denk = getImage(denk)

    for werk in verlag:
        werk.desc = addLinks(werk.desc)
        for aut in werk.denker.all():
            if werk.author is not "":
                werk.author += ", "
            werk.author += "<a class='link' href='" + reverse('denker:detail', kwargs={'denker_slug': aut.slug}) + "'><h6 lass='h-left' style='text-align: left;'>" + aut.name + "</h6></a>"

    projekt.beschreibung = addLinks(projekt.beschreibung)
    projekt = getPercent(projekt)

    literatur = createLink(literatur)

    tagesbezogenes = getDays()
    heute = ""
    if tagesbezogenes[0] or tagesbezogenes[1]:
        locale.setlocale(locale.LC_TIME, "de_DE.UTF-8")
        heute = datetime.datetime.strftime(datetime.date.today(), "%A, der %d. %B")
        daymatch = True
    else:
        daymatch = False

    context = {
        'infotext': infotext,
        'denker': denker,
        'verlag': verlag,
        'projekt': projekt,
        'literatur': literatur,
        'daymatch': daymatch,
        'geboren': tagesbezogenes[0],
        'gestorben': tagesbezogenes[1],
        'heute': heute,
    }

    return render(request, 'framework/home-view.html', context)

framework/templates/framework/components/base.html
<!DOCTYPE html>
<html lang="de">
<head>
  {% load static %}
  <meta charset="UTF-8">
  <meta name="description" content="Verlag und Kompendium zur &Ouml;stereichischen Schule der &Ouml;konomik">
  <link rel="shortcut icon" type="image/png" href="{% static '/framework/images/favicon.ico' %}" sizes="32x32">  
  
  <!--link rel="apple-touch-icon" sizes="180x180" href="..\apple-touch-icon.png"> TODO: Übertragen
  <meta name="msapplication-TileColor" content="#ffffff">
  <meta name="msapplication-TileImage" content="..\mstile-144x144.png">
  <meta name="viewport" content="width=device-width, initial-scale=1"-->
  
  <link rel="stylesheet" href="{% static '/framework/style/normalize.css' %}">
  <link href="https://fonts.googleapis.com/css?family=Raleway:400,300|EB+Garamond" rel="stylesheet" type="text/css">
  <link rel="stylesheet" href="{% static '/framework/style/style.css' %}">
  
  <title>
    {% block title %}Mises Austria{% endblock title %}
  </title>
  
</head>
<body>
  {% include "framework/components/header.html" %}
  
  {% block content %}
  {% endblock content %}
  
  {% include "framework/components/footer.html" %}
  
  
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.2/jquery.min.js"></script>
  <script src="{% static '/framework/js/general.js' %}"></script>
  <script src="{% static '/framework/js/sorttable.js' %}"></script>
</body>

</html>

framework/templates/framework/components/footer.html
<footer id="footer">
  <p>&copy; mises.at 2015-2017 <!--&mdash; <a href="../verlag/impressum.php">Impressum</a> <a href="../verlag/index.php">&Uuml;ber Uns</a--></p>
  <script>
    (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
    (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
    m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
    })(window,document,'script','https://www.google-analytics.com/analytics.js','ga');

    ga('create', 'UA-99991152-1', 'auto');
    ga('send', 'pageview');
  </script>
</footer>

framework/templates/framework/components/header.html
{% load static %}
<header id="header">
  <div class="logo">
    <a href="{% url 'framework:home' %}"><img src="{% static '/framework/images/ma_logo_text.png' %}" alt=""></a>
  </div>
  <div class="nav-trigger">
    <div class="nav-trigger__icon">
      <a href="#" onclick="showNav();return false;"><img src="{% static '/framework/images/navicon.svg' %}" alt="Menu" title="Menu"></a>
    </div>
  </div>
  <div id="nav">
    <div class="navi">
      <ul>
        <li><a href="{% url 'verlag:list' %}" onclick="showNav();">Verlag</a></li>
        <li><a href="{% url 'denker:list' %}" onclick="showNav();">Denker</a></li>
        <li><a href="{% url 'literatur:list' %}" onclick="showNav();">Literatur</a></li>
        <li><a href="{% url 'orte:map' %}" onclick="showNav();">Orte</a></li>
        <li><a href="{% url 'projekte:list' %}" onclick="showNav();">Projekte</a></li>
        <li><a href="{% url 'faq:list' %}" onclick="showNav();">Glossar</a></li>
      </ul>
    </div>
  </div>
</header>