denker/urls.py
from django.conf.urls import url
from .views import detail_view, list_view

app_name = 'denker'

urlpatterns = [
    url(r'^(?P<denker_slug>[\w-]+)/$', detail_view, name='detail'),
    url(r'^$', list_view, name='list'),
]

faq/urls.py
from django.conf.urls import url
from .views import list_view

app_name = 'faq'

urlpatterns = [
    # url(r'^(?P<tag>#[\w-]+)$', list_view, name='list'),
    url(r'^$', list_view, name='list'),
]

framework/urls.py
from django.conf.urls import url
from .views import home_view
from django.http import HttpResponse

app_name = 'framework'

urlpatterns = [
    url(r'^$', home_view, name='home'),
    url(r'^googlee50af1936941f141.html$', lambda request: HttpResponse('google-site-verification: googlee50af1936941f141.html'))
]

orte/urls.py
from django.conf.urls import url
from .views import map_view, detail_view

app_name = 'orte'

urlpatterns = [
    url(r'^(?P<ort_slug>[\w-]+)/$', detail_view, name='detail'),
    url(r'^$', map_view, name='map'),
]

orte/models.py
from django.db import models
from django.utils.text import slugify


class Orte(models.Model):
    id = models.AutoField(primary_key=True)
    slug = models.SlugField(allow_unicode=True, unique=True, max_length=250, null=True, blank=True)
    name = models.CharField(max_length=250)
    img = models.CharField(max_length=500)
    text = models.TextField()
    text_en = models.TextField()
    lat = models.FloatField()
    lng = models.FloatField()
    denker_slugs = models.CharField(max_length=500)
    denker = models.ManyToManyField('denker.Denker')

    def __str__(self):
        return (str(self.id) + " | " + str(self.name))

    class Meta:
        managed = True
        db_table = 'orte'
        verbose_name = 'Ort'
        verbose_name_plural = 'Orte'

    def pre_save_receiver(sender, instance, *args, **kwargs):
        if not instance.slug and instance.titel:
            instance.slug = slugify(instance.name.rsplit(None, 1)[1])

orte/views.py
from django.shortcuts import render, get_object_or_404
from .models import Orte
from framework.views import addLinks


def map_view(request):
    orte = Orte.objects.all()
    for ort in orte:
        ort.text = addLinks(ort.text, ort.slug)
    context = {
        "orte": orte,
    }
    return render(request, 'orte/map-view.html', context)
    

def detail_view(request, ort_slug):
    ort = get_object_or_404(Orte, slug=ort_slug)
    ort.text = addLinks(ort.text, ort.slug)
    return render(request, 'orte/detail-view.html', {'ort': ort})

orte/templates/orte/base-view.html
{% extends "framework/components/base.html" %}

{% block title %}Orte | {{ block.super }}{% endblock title %}

{% block content %}
  <h1>Orte Base</h1>
{% endblock content %}

orte/templates/orte/detail-view.html
{% extends "orte/base-view.html" %}

{% block content %}
{% load static %}

  <div id="content">
      <div class="container index-link"><p><a href="{% url 'framework:home' %}">mises.at</a> / <a href="{% url 'orte:map' %}">Orte</a> / {{ ort.name }}</p></div>
      <div class="container">
        <div class="row">
          <div class="two-thirds column">
            <h1>{{ ort.name }}</h1>
          </div>
          <div class="one-third column h-white">
            <img src="{{ ort.img }}" class="img--coat" alt=".">
          </div>
        </div>
      </div>
      
      <div class="container text">
          <h2>Beschreibung</h2>
          <p>{{ ort.text|safe }}</p>
      </div>
  </div>
      
{% endblock content %}

orte/templates/orte/map-view.html
{% extends "orte/base-view.html" %}

{% block content %}
{% load static %}
{% load replace_linebr %}

<div class="map">
  <div id="map" class="map__map"></div>
</div>
<script type="text/javascript">

function initMap() {
  
  var MisesAustriaMapStyle = new google.maps.StyledMapType([
    {
    }
  ], {name: 'Wohn- und Wirkungsorte Wiener Denker'});
  
  var map = new google.maps.Map(document.getElementById('map'), {
    center: {lat: 48.0596696, lng: 14.4656239},
    zoom: 5,
    mapTypeControlOptions: {
      mapTypeIds: [google.maps.MapTypeId.ROADMAP, 'misesat_map']
    }
  });
  
  map.mapTypes.set('misesat_map', MisesAustriaMapStyle);
  map.setMapTypeId('misesat_map');
  
  {% for ort in orte %}
    {% with ort.text|length as length %}
      {% with ort.denker.all|length as denker_length %}
        var url = "{% url 'orte:detail' ort_slug=ort.slug %}";
        var denkerList = "";
        {% for denk in ort.denker.all %}
          {% if forloop.counter0 > 0 %} 
            denkerList += ", "
          {% endif %}
          var denker_url = "{% url 'denker:detail' denker_slug=denk.slug %}";
          var link = '<a href="' + denker_url + '">{{ denk.name }}</a>';
          denkerList += link;
        {% endfor %}
        
        var contentString = '<div class="map-info">'+
        '<a href="'+url+'"> <h2>{{ ort.name }}</h2></a>'+
        '<a href="'+url+'"> <img src="{{ ort.img }}" alt="."></a>'+
        '<p>{{ ort.text|safe|truncatewords_html:40 }}</p>'+
        '<h6>Denker, die hier gelebt und gewirkt haben</h6><p>'+
        denkerList + 
        '</p></div>'+
        '<div class="card-link h-right"><a href="'+url+'">Mehr</div>';
        
        
        //var contentString = join()
        
        var marker = new google.maps.Marker({
          position: {lat: {{ ort.lat }}, lng: {{ ort.lng }}},
          map: map,
          title: '{{ ort.name }}'
        });
        var infowindow = null;
        attachInfoWindow(marker, contentString);
      {% endwith %}
    {% endwith %}
  {% endfor %}
  
  function attachInfoWindow(marker, info) {
    
    marker.addListener('click', function() {
      
      if (infowindow) {
        infowindow.close();
      }
      infowindow = new google.maps.InfoWindow({
        content: info
      });
      infowindow.open(map, marker);
      
    });
    
  }
}

</script>

<script async defer
src="https://maps.googleapis.com/maps/api/js?key=AIzaSyChP6VPcxuqcO5r8q7733mF7hzjNg4r9EY&callback=initMap">
</script>

{% endblock content %}