denker/urls.py
from django.conf.urls import url
from .views import detail_view, list_view

app_name = 'denker'

urlpatterns = [
    url(r'^(?P<denker_slug>[\w-]+)/$', detail_view, name='detail'),
    url(r'^$', list_view, name='list'),
]

faq/urls.py
from django.conf.urls import url
from .views import list_view

app_name = 'faq'

urlpatterns = [
    # url(r'^(?P<tag>#[\w-]+)$', list_view, name='list'),
    url(r'^$', list_view, name='list'),
]

framework/urls.py
from django.conf.urls import url
from .views import home_view
from django.http import HttpResponse

app_name = 'framework'

urlpatterns = [
    url(r'^$', home_view, name='home'),
    url(r'^googlee50af1936941f141.html$', lambda request: HttpResponse('google-site-verification: googlee50af1936941f141.html'))
]

projekte/urls.py
from django.conf.urls import url
from .views import list_view, detail_view

app_name = 'projekte'

urlpatterns = [
    url(r'^$', list_view, name='list'),
    url(r'^(?P<projekt_slug>[\w-]+)/$', detail_view, name='detail'),
]

projekte/models.py
from django.db import models
from django.db.models.signals import pre_save
from django.utils.text import slugify
from django.utils.timezone import now


class Projekte(models.Model):
    id = models.AutoField(primary_key=True)
    slug = models.SlugField()
    titel = models.TextField()
    autor = models.TextField(null=True, blank=True)
    autor_id = models.TextField(null=True, blank=True)
    beschreibung = models.TextField()
    spenden = models.IntegerField()
    ziel = models.IntegerField()
    author = models.ForeignKey('denker.Denker', on_delete=models.PROTECT, null=True, blank=True)

    @property
    def fehlend(self):
        return self.ziel - self.spenden

    def __str__(self):
        return (str(self.id) + " | " + str(self.author) + ": " + str(self.titel) + " (" + str(self.ziel) + " )")

    class Meta:
        managed = True
        db_table = 'projekte'
        verbose_name = 'Projekt'
        verbose_name_plural = 'Projekte'


def pre_save_receiver(sender, instance, *args, **kwargs):
    if not instance.slug and instance.name:
        instance.slug = slugify(instance.titel.rsplit(None, 1)[1])


pre_save.connect(pre_save_receiver, sender=Projekte)


class Stufen(models.Model):
    betrag = models.IntegerField()
    vorteile = models.TextField()
    projekt = models.ForeignKey('projekte.Projekte', on_delete=models.CASCADE)
    
    def __str__(self):
        return str(self.betrag) + "eur @ " + str(self.projekt.titel)


class Spenden(models.Model):
    Vorname = models.CharField(max_length=100)
    Nachname = models.CharField(max_length=100)
    Email = models.EmailField()
    Stufe = models.ForeignKey('Stufen', on_delete=models.PROTECT)
    Datum = models.DateTimeField(default=now)
    Validiert = models.BooleanField(default="False")
    
    def __str__(self):
        return str(self.Vorname) + " " + str(self.Nachname) + " | " + str(self.Stufe)
    

projekte/forms.py
from django import forms
from .models import Spenden, Stufen
from django.db.models.signals import pre_save
import pprint


class StufenModelChoiceField(forms.ModelChoiceField):
    def label_from_instance(self, obj):
        return str(obj.betrag) + "€"

class SpendenModelForm(forms.ModelForm):
    Vorname = forms.CharField(widget=forms.TextInput(attrs={'placeholder': 'Vorname'}))
    Nachname = forms.CharField(widget=forms.TextInput(attrs={'placeholder': 'Nachname'}))
    Email = forms.EmailField(widget=forms.TextInput(attrs={'placeholder': 'Email'}))
    
    class Meta():
        model = Spenden
        fields = [
            "Vorname",
            "Nachname",
            "Email",
            "Stufe"
        ]
        
    Stufe = StufenModelChoiceField(queryset=Stufen.objects.all(), empty_label="Stufe wählen")
        
    def __init__(self, projekt, *args, **kwargs):
        super(SpendenModelForm, self).__init__(*args, **kwargs)
        self.fields['Stufe'].queryset = Stufen.objects.filter(projekt = projekt)

projekte/views.py
from django.shortcuts import render, get_object_or_404
from .models import Projekte, Stufen
from framework import views
from .utils import getPercent
from .forms import SpendenModelForm
from django.http import HttpResponse
import pprint


def list_view(request):
    projekte = list(Projekte.objects.all().order_by('-id'))
    for p in projekte:
        p.beschreibung = views.addLinks(p.beschreibung)
        p = getPercent(p)
        
    return render(request, 'projekte/list-view.html', {'projekte': projekte})


def detail_view(request, projekt_slug):
    projekt = get_object_or_404(Projekte, slug=projekt_slug)
    stufen = Stufen.objects.filter(projekt=projekt)
    stufenList = list(stufen)
    projekt.beschreibung = views.addLinks(projekt.beschreibung)
    projekt = getPercent(projekt)

    fields = 100
    if stufenList:
        fields = fields/len(stufenList)

    spendenForm = SpendenModelForm(get_object_or_404(Projekte, slug=projekt_slug), request.POST or None)
    
    if spendenForm.is_valid():
        spendenForm.save()
        print("SAVING")
        return payment_view(request)
    else:
        print('NOT SAVING')
        print(spendenForm.errors)
    
    context = {
        "stufen": stufenList,
        "fields": fields,
        "projekt": projekt,
        "spendenform": spendenForm,
    }
    return render(request, 'projekte/detail-view.html', context)
    

def payment_view(request):
    pprint.pprint(request.POST['Stufe'])
    context = {
        "stufe": Stufen.objects.get(pk = int(request.POST['Stufe'])),
    }
    return render(request, 'projekte/payment-view.html', context)
    # return HttpResponse(request.POST['projekt'])

projekte/templates/projekte/base-view.html
{% extends "framework/components/base.html" %}

{% block title %}Projekte | {{ block.super }}{% endblock title %}

{% block content %}
  <h1>Projekte Base</h1>
{% endblock content %}

projekte/templates/projekte/detail-view.html
{% extends "projekte/base-view.html" %}

{% block content %}
{% load static %}

<link rel="stylesheet" href="{% static '/projekte/css/box.css' %}">

<div id="content">
  <div class="container index-link"><p><a href="{% url 'framework:home' %}">mises.at</a> / <a href="{% url 'projekte:list' %}">Projekte</a> / {{ projekt.titel }}</p></div>
  <div class="container">
    <div class="row style-space--bottom">
      <h1>{{ projekt.titel }}</h1>
    </div>
    <div class="one-third column h-centered">
    </div>
  </div>
  <h2>Beschreibung</h2>
  <p>{{ projekt.beschreibung |safe}}</p>

  <div class="container">
    <br>
    <progress value="{{ projekt.prozent }}" max="100"></progress>

    <p class=""><b>{{ projekt.prozent|floatformat:1 }}%</b> finanziert{% if projekt.ziel > projekt.spenden %} - Noch {{ projekt.fehlend }}€ bis zum Finanzierungsziel{% endif %}</p>
    <br>
  </div>
  <div class="h-centered" style="width: 100%">
    <h3>Dieses Projekt unterstützen</h3>
  </div>

  <div class="container grid" style="justify-content: center;">
    <button class="btn-donate btn-link button-text" onclick="window.location.href='mailto:&#105;nf&#111;&#064;&#109;&#105;se&#115;.&#97;&#116;'">Kontakt</button>
    <form name="_xclick" action="https://www.paypal.com/at/cgi-bin/webscr" method="post">
      <input type="hidden" name="cmd" value="_xclick">
      <input type="hidden" name="business" value="info@scholarium.at">
      <input type="hidden" name="item_name" value="Spende_{{ projekt.slug }}">
      <input type="hidden" name="currency_code" value="EUR">
      <input id="pp_amount" type="hidden" name="amount" value="{{ stufe.betrag }}">
      <input type="hidden" name="shipping" value="0">
      <input type="hidden" name="no_shipping" value="1">
      <button type="submit" name="submit" class="btn-btc btn-link h-block button-text" style="background-image: url({% static '/projekte/images/PayPal.svg' %}); background-position: center; width: 14em;">
    </form>
  </div>
  {% if stufen %}
  
  <div style="display: block; width: 100%; overflow: hidden;">
  <div class="centered" style="max-width: 20em; padding: 5px;">
    <div class="" style="width: 100%; display: block; float: left;">
    

      <form method="POST">{% csrf_token %}
        {{ spendenform.non_field_errors }}
        <div class="fields">
          {{ spendenform.Vorname.errors }}
          {{ spendenform.Vorname }}
          {{ spendenform.Nachname.errors }}
          {{ spendenform.Nachname }}
          {{ spendenform.Email.errors }}
          {{ spendenform.Email }}
          {{ spendenform.Stufe.errors }}
          <div id="stufenselect">{{ spendenform.Stufe }}</div>
          <input type="submit" class="centered h-extra-space__top" value="Abschicken">
        </div>
      </form>
    
    </div>
    
  </div>
</div>
  <div class="" style="margin-right: 10%; margin-left: 10%;">
    <h3 style="text-align: center;" class="h-extra-space__top h-extra-space__bottom">Unterstützungsstufen</h3>
      {% for stufe in stufen %}
        <div style="display: block; width: {{ fields }}%; float: left;"><div><h4 style="text-align: center;">{{ stufe.betrag }}€</h4></div><div class="vorteil">{{ stufe.vorteile }}</div></div>
      {% endfor %}
  </div>
{% endif %}
</div>


{% endblock content %}

projekte/templates/projekte/list-view.html
{% extends "projekte/base-view.html" %}

{% block content %}
{% load static %}

<div id="content">
  
  <div class="container index-link"><p><a href="{% url 'framework:home' %}">mises.at</a> / Projekte</p></div>
  <div class="container">
    <h1>Projekte</h1>
    <p>Hier finden Sie eine &Uuml;bersicht unserer aktuellen Projekte.</p>
  </div>
  
  <div class="container h-centered style-space--bottom ">
    <div class="grid">
      
      {% for projekt in projekte %}
      <div class="card projectcard" style="order: {{ projekt.order }};">
        <div class="card-content">
          <div class="list-itm h-extra-space__top">
            <a class="link" href="{% url 'projekte:detail' projekt_slug=projekt.slug %}"><h3 class="titel">{{ projekt.titel }}</h3></a><br>
            {% if projekt.author %}
              <a class="link" href="{% url 'denker:detail' denker_slug=projekt.author.slug %}"><h6 class="h-left" style="text-align: left;">{{ projekt.author.name }}</h6></a>
            {% else %}
              <h6 class="h-left" style="text-align: left;">{{ projekt.autor }}</h6>
            {% endif %}
            <p>{{ projekt.beschreibung|safe|truncatewords_html:40 }}</p>
          </div>
          <div class="">
            
            <div class="">
              <progress value="{{ projekt.prozent }}" max="100"></progress>
              
              <p class=""><b>{{ projekt.prozent|floatformat:1 }}%</b> finanziert{% if projekt.ziel > projekt.spenden %} - Noch {{ projekt.fehlend }}€ bis zum Finanzierungsziel{% endif %}</p>
              <br>
              
            </div>
          </div>
        </div>
      </div>
      {% endfor %}
      <div class="projectcard" style="order: 100"></div>
      <div class="projectcard" style="order: 100"></div>
      <div class="projectcard" style="order: 100"></div>
    </div>
    <br><br><br><br>
    <a class="btn-link h-block button-text h-centered" href="mailto:&#105;nf&#111;&#064;&#109;&#105;se&#115;.&#97;&#116;">Kontakt</a>
  </div>
</div>

{% endblock content %}

projekte/templates/projekte/payment-view.html
{% extends "projekte/base-view.html" %}

{% block content %}
{% load static %}

<link rel="stylesheet" href="{% static '/projekte/css/box.css' %}">

<div id="content">
  <div class="container index-link"><p><a href="{% url 'framework:home' %}">mises.at</a> / <a href="{% url 'projekte:list' %}">Projekte</a> / {{ stufe.projekt.titel }}</p></div>
  <div class="container">
    <div class="row style-space--bottom">
      <h1 style="text-align: center;">Vielen Dank für Ihre Unterstützung!</h1>
    </div>
  </div>

<div class="container grid" style="justify-content: center;">
  <button class="btn-donate btn-link button-text" onclick="window.location.href='mailto:&#105;nf&#111;&#064;&#109;&#105;se&#115;.&#97;&#116;'">Kontakt</button>

  <button id="show" class="btn-btc btn-link h-block button-text" style="background-image: url({% static '/projekte/images/bitcoin.svg' %})">
    <a style="padding-left:2.5em;">Bitcoin-Adresse</a>

  </button>

<button id="show2" class="btn-btc btn-link h-block button-text">
  <a>Bank-Überweisung</a>
</button>


<form name="_xclick" action="https://www.paypal.com/at/cgi-bin/webscr" method="post">
  <input type="hidden" name="cmd" value="_xclick">
  <input type="hidden" name="business" value="info@scholarium.at">
  <input type="hidden" name="item_name" value="Spende">
  <input type="hidden" name="currency_code" value="EUR">
  <input id="pp_amount" type="hidden" name="amount" value="{{ stufe.betrag }}">
  <button type="submit" name="submit" class="btn-btc btn-link h-block button-text" style="background-image: url({% static '/projekte/images/PayPal.svg' %}); background-position: center; width: 14em;">
</form>

</div>




<dialog id="btcdialog">
  <div class="card-content">
    <img src="{% static '/projekte/images/wallet.png' %}" style="width:100%;"/>
    <p>16wWd9Znzv5oN3ag7A47sezdLbUCm32Tt4</p>
    <p class="h-centered">Vielen Dank für Ihre Unterstützung!</p>
  </div>
  <div class="card-link h-right">
    <a id="close" style="cursor: pointer;">Schließen</a>
  </div>
</dialog>
<dialog id="bankdialog">
  <div class="card-content">
    <p class="h-centered"><b>Erste Bank</b></p>

    <p><b>Kontonummer:</b> 28824799900<br>
    <b>Bankleitzahl:</b> 20111<br>
    <b>IBAN:</b> AT332011128824799900<br>
    <b>BIC:</b> GIBAATWW<br>
    <b>Betreff:</b> Spende {{ stufe.projekt.slug }}</p>

    <p class="h-centered">Vielen Dank für Ihre Unterstützung!</p>
  </div>
  <div class="card-link h-right">
    <a id="close2" style="cursor: pointer;">Schließen</a>
  </div>
</dialog>
</div>

<script src="{% static '/projekte/js/box.js' %}"></script>

{% endblock content %}