denker/urls.py
from django.conf.urls import url
from .views import detail_view, list_view

app_name = 'denker'

urlpatterns = [
    url(r'^(?P<denker_slug>[\w-]+)/$', detail_view, name='detail'),
    url(r'^$', list_view, name='list'),
]

faq/urls.py
from django.conf.urls import url
from .views import list_view

app_name = 'faq'

urlpatterns = [
    # url(r'^(?P<tag>#[\w-]+)$', list_view, name='list'),
    url(r'^$', list_view, name='list'),
]

framework/urls.py
from django.conf.urls import url
from .views import home_view
from django.http import HttpResponse

app_name = 'framework'

urlpatterns = [
    url(r'^$', home_view, name='home'),
    url(r'^googlee50af1936941f141.html$', lambda request: HttpResponse('google-site-verification: googlee50af1936941f141.html'))
]

literatur/urls.py
from django.conf.urls import url
from .views import list_view, denker_view

app_name = 'literatur'

urlpatterns = [
    url(r'^(?P<denker_slug>[\w-]+)/$', denker_view, name='denker'),
    url(r'^$', list_view, name='list'),
]

denker/models.py
from django.db import models
from django.db.models.signals import pre_save
from django.utils.text import slugify


class Denker(models.Model):
    id = models.AutoField(primary_key=True)
    slug = models.CharField(max_length=250, unique=True, null=True, blank=True)
    name = models.CharField(max_length=250)
    img = models.CharField(max_length=250)
    bio = models.TextField()
    bio_en = models.TextField(null=True, blank=True)
    geburt = models.DateField(null=True, blank=True)
    tod = models.DateField(null=True, blank=True)
    gen = models.IntegerField()

    class Meta:
        managed = True
        db_table = 'denker'
        verbose_name = 'Denker'
        verbose_name_plural = 'Denker'

    def __str__(self):
        return self.name
        

def pre_save_receiver(sender, instance, *args, **kwargs):
    if not instance.slug and instance.name:
        instance.slug = slugify(instance.name.rsplit(None, 1)[1])


pre_save.connect(pre_save_receiver, sender=Denker)

denker/views.py
from django.shortcuts import render, get_object_or_404
from .models import Denker
from literatur.views import gen_werke
from framework.views import addLinks
from .utils import getImage


def list_view(request):
    qs = list(Denker.objects.order_by('slug'))
    gen = ["menger", "bawerk", "mises", "rothbard"]
    letters = []
    letter_last = ""
    
    for denker in qs:
        firstletter = denker.slug[:1]
        
        if firstletter != letter_last:
            letters.append(firstletter.upper())
            letter_last = firstletter
            
        denker.firstletter = firstletter.upper()
        denker = getImage(denker)
    
    context = {
        "gen": gen,
        "denker_list": qs,
        "denker_bybirth": sorted(qs, key=lambda x: x.geburt), 
        "letters": letters,
    }
    return render(request, 'denker/list-view.html', context)


def detail_view(request, denker_slug):
    denker = getImage(get_object_or_404(Denker, slug=denker_slug))
    werke = gen_werke(denker)
    denker.bio = addLinks(denker.bio, denker.slug)
    
    context = {
        'denker': denker,
        'werke': werke[:10]
    }
    
    return render(request, 'denker/detail-view.html', context)

denker/templates/denker/base-view.html
{% extends "framework/components/base.html" %}

{% block title %}Denker | {{ block.super }}{% endblock title %}

{% block content %}
  <h1>Denker Base</h1>
{% endblock content %}

denker/templates/denker/detail-view.html
{% extends "denker/base-view.html" %}

{% block content %}
{% load static %}

<div id="content">
        <div class="container index-link"><p><a href="{% url 'framework:home' %}">mises.at</a> / <a href="{% url 'denker:list' %}">Denker</a> / {{ denker.name }}</p></div>
        <div class="container">
          <div class="row style-space--bottom">
            <div class="two-thirds column">
              <h1>{{ denker.name }}</h1>
            </div>
            <div class="one-third column h-centered">
              <img src="{% static 'denker/images/'|add:denker.image|add:'.jpg' %}" class="img--portrait" alt="{{ denker.name }}"/>
    
            </div>
          </div>
          <div class="row">
            <div class="two-thirds column text">
              <h2>Leben</h2>
              <p>{{ denker.bio |safe}}</p>
            </div>
            <div class="one-third column">
              <h5 class="style-bl--red">Werke</h5>
              <div class="list">
                  <ul class="list--none">
                    {% for werk in werke %}
                    <li>
                      {% if werk.quelle %}
        							<a class="" target="_blank" href="{{ werk.link }}">{{ werk.titel|safe }}</a> ({{ werk.jahr }})
                      {% else %}
                      <div class="list_title">{{ werk.titel|safe }} ({{ werk.jahr }})</div> 
                      {% endif %}
                    </li>
                    {% endfor %}
                  </ul>
              </div>
              
              <div class="h-centered h-extra-space__top">
                <a class="btn-link h-block" href="{% url 'literatur:denker' denker_slug=denker.slug %}">gesamte Liste</a>
              </div>
            </div>
          </div>
        </div>
      </div>
{% endblock content %}

denker/templates/denker/list-view.html
{% extends "denker/base-view.html" %}

{% block content %}
{% load static %}
<div id="content">
    <div class="container index-link"><p><a href="{% url 'framework:home' %}">mises.at</a> / Denker</p></div>
    <div class="container">
      <h1>Denker</h1>
      <p>Hier finden Sie eine umfassende &Uuml;bersicht der in der Denktradition der &Ouml;sterreichischen Schule stehenden Denker.</p>
    </div>

    <div class="container">
      
      <div class="itm-index">
        {% for letter in letters %}
        <div class="dropdown">
          <button class="dropbtn">
            {{ letter }}
          </button>
          <div class="dropdown-content">
            {% for denker in denker_list %}
              {% if denker.firstletter == letter %}
                <a href="#{{ denker.slug }}">{{ denker.name }}</a>
              {% endif %}
            {% endfor %}
          </div>
        </div>
        {% endfor %}
      </div>
      
      <ul class="grid gengrid h-centered">
        {% for i in gen %}
          <li class="gencell">
            <a href="#{{ i }}">
              <div class="card button-card">
                <img class="card-head button-img" src="{% static 'denker/images/buttons/'|add:i|add:'2.jpg' %}"/>
              </div>
              <h6 class="button-title">{{ forloop.counter }}. Generation</h6>
            </a>
          </li>
        {% endfor %}
      </ul>
      
      <ul class="grid">
        {% for denker in denker_bybirth %}
        {% url 'denker:detail' denker_slug=denker.slug as denker_url %}
        
          <li class="card denkercell" id="{{ denker.slug }}">
            <a href="{{ denker_url }}">	
              <div class="card-head card-head__overlay">
                <img src="{% static 'denker/images/'|add:denker.image|add:'.jpg' %}" alt="{{ denker.name }}">
              </div>
            </a>
                
          <div class="card-content">
            <h6> <a href="{{ denker_url }}">{{ denker.name }}</a></h6>
            <p>{{ denker.bio|safe|truncatewords_html:40 }}</p>
          </div>
                
          <div class="card-link h-right">
            <a href="{{ denker_url }}">Zur Person</a>
          </div>
        </li>
      {% endfor %}
      
      <li class="card denkercell" style="height:0;"></li>
      <li class="card denkercell" style="height:0;"></li>
      <li class="card denkercell" style="height:0;"></li>
      
    </ul>
    
  </div>
</div>
      
{% endblock content %}